[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false
decorations = "none"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
